events {}
        http {
            upstream app_backend {
                server ai-enhanced-devops-assistant-app-3:5000;
        server ai-enhanced-devops-assistant-app-2:5000;
        server ai-enhanced-devops-assistant-app-1:5000;
    }
            server {
                listen 80;
                location / {
                    proxy_pass http://app_backend;
                }
            }
        }