# Tells Prometheus what to scrape
1.  global:
2.    scrape_interval: 5s
3.  
4.  rule_files:
5.    - 'alert_rules.yml'
6.  
7.  alerting:
8.    alertmanagers:
9.      - static_configs:
10.         targets: ['alertmanager:9093']
11. 
12. scrape_configs:
13.   - job_name: 'target_app'
14.     static_configs:
15.       - targets: ['app:5000']